# PROGRAM-ID: fermat
# AUTHOR: anonimo
#!/usr/bin/env python3
# Generated by COBOL-85 to Python compiler
import sys
def fermat():
    n_input = None
    n = 3
    total = 3
    x = None
    y = None
    z = None
    exp_x = None
    exp_y = None
    exp_z = None
    suma = None
    ws_base = None
    ws_exp = None
    ws_result = None
    ws_j = None
    
    def main_procedure():
        nonlocal n_input, n, total, x, y, z, exp_x, exp_y, exp_z, suma, ws_base, ws_exp, ws_result, ws_j
        n_input = int(input())
        n = n_input
        para_100_main_loop()
        sys.exit(0)
    
    
    def para_100_main_loop():
        nonlocal n_input, n, total, x, y, z, exp_x, exp_y, exp_z, suma, ws_base, ws_exp, ws_result, ws_j
        while not (1 == 0):
            x = 1
            while not (x > total - 2):
                y = 1
                while not (y > total - x - 1):
                    z = total - x - y
                    ws_base = x
                    ws_exp = n
                    calcula_exp()
                    exp_x = ws_result
                    ws_base = y
                    ws_exp = n
                    calcula_exp()
                    exp_y = ws_result
                    ws_base = z
                    ws_exp = n
                    calcula_exp()
                    exp_z = ws_result
                    suma = exp_x + exp_y
                    if suma == exp_z:
                        print("hola, mundo")
                    y += 1
                x += 1
            total += 1
    
    
    def calcula_exp():
        nonlocal n_input, n, total, x, y, z, exp_x, exp_y, exp_z, suma, ws_base, ws_exp, ws_result, ws_j
        ws_result = 1
        ws_j = 1
        while not (ws_j > ws_exp):
            ws_result = ws_result * ws_base
            ws_j += 1
    
    main_procedure()  # Llamada a la función principal

# END PROGRAM fermat

if __name__ == '__main__':
    fermat()
